version: '2'

services:
  # ============================= Rocketchat ==================================
  rocketchat:
    image: rocket.chat:0.69.2
    restart: unless-stopped
    env_file:
      - ./rocketchat.env
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    command: mongod --smallfiles --oplogSize 128

volumes:
  mongo_data:
